[tool.poetry]
name = "grabit"
version = "1.3.2"
description = "Simple Python CLI tool for turning directories into a single text file for input to LLMs."
authors = ["Connor Skelland <34070858+Connor56@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://github.com/Connor56/grabit"
repository = "https://github.com/Connor56/grabit"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.scripts]
grabit = "grabit.grabit:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
