[project]
name = "EasyMinecraftServer"
version = "0.0.3"
description = "A Typer app that makes the creation process of a Minecraft Server easier!"
license = "GPL-3.0-only"
authors = [
    { name = "Nucceteere", email = "ruzgar@nucceteere.xyz" }
]
keywords = [ "game", "minecraft", "game server", "server", "fabric", "forge", "neoforge", "paper", "purpur", "spigot" ]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer (>=0.15.2,<0.16.0)",
    "pathvalidate (>=3.2.3,<4.0.0)",
    "psutil (>=7.0.0,<8.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "javaproperties (>=0.8.2,<0.9.0)"
]
dynamic = [ "classifiers" ]

[project.urls]
homepage = "https://git.funtimes909.xyz/Nucceteere/EasyMinecraftServer/src/branch/main/README.md"
repository = "https://git.funtimes909.xyz/Nucceteere/EasyMinecraftServer/"
documentation = "https://git.funtimes909.xyz/Nucceteere/EasyMinecraftServer/wiki/"
"Bug Tracker" = "https://git.funtimes909.xyz/Nucceteere/EasyMinecraftServer/issues"
"Contribute" = "https://git.funtimes909.xyz/Nucceteere/EasyMinecraftServer/pulls"

[tool.poetry]
packages = [
    { include = "EasyMinecraftServer" },
]
requires-poetry = ">=2.0"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Information Technology",
    "Natural Language :: English",
    "Natural Language :: Turkish",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Topic :: Games/Entertainment",
    "Topic :: Utilities"
]

[project.scripts]
easy-minecraft-server = "EasyMinecraftServer.main:app"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pre-commit = "^4.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
