[project]
name = "comfydock"
version = "0.1.9"
description = "ComfyDock CLI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "comfydock-server>=0.1.5",
    "packaging>=24.2",
    "python-dotenv>=1.0.1",
]

[project.scripts]
comfydock = "comfydock.cli:main"
