[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "doctestcase"
description = "Evaluate doctests with configurable globals and `setUp`‚Äì`tearDown`. Export to Markdown and reST to include in docs."
authors = [
  {name = "Michael Makukha", email = "m.makukha@gmail.com"},
]
license = {text = "MIT"}
readme = "README.md"
urls.Documentation = "https://doctestcase.readthedocs.io"
urls.Homepage = "https://github.com/makukha/doctestcase"
urls.Repository = "https://github.com/makukha/doctestcase"
urls.Issues = "https://github.com/makukha/doctestcase/issues"
urls.Changelog = "https://github.com/makukha/doctestcase/blob/main/CHANGELOG.md"
keywords = ["unittest", "doctest", "test-case", "markdown", "rst", "restructuredtext"]
classifiers = [
  # see https://pypi.org/classifiers/
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 2",
  "Programming Language :: Python :: 2.7",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Documentation",
  "Topic :: Software Development",
  "Topic :: Software Development :: Libraries",
  "Typing :: Typed",
]
dynamic = ["version"]

requires-python = ">=2.7,!=3.0,!=3.1,!=3.2,!=3.3,!=3.4"
dependencies = []

[dependency-groups]
dev = [
  "bump-my-version>=0.33 ; python_version >= '3.13'",
  "docsub>=0.9.0 ; python_version >= '3.13'",
  "genbadge[tests,coverage]>=1.1 ; python_version >= '3.13'",
  "mypy>=1.15 ; python_version >= '3.13'",
  "ruff>=0.9 ; python_version >= '3.13'",
  "scriv>=1.5 ; python_version >= '3.13'",
]
docs = [
  # see readthedocs.yaml
  "furo ; python_version >= '3.12'",
  "myst-parser ; python_version >= '3.12'",
  "sphinx ; python_version >= '3.12'",
  "sphinx-copybutton ; python_version >= '3.12'",
  "sphinx-design ; python_version >= '3.12'",
  "sphinx-sitemap ; python_version >= '3.12'",
]
testing = [
  "docsub>=0.9.0 ; python_version >= '3.9'",  # used in tests
  "doctestcase>=0.2.1",
  "mypy ; python_version >= '3.8'",  # see tox.ini
  "pytest>=8 ; python_version >= '3.8'",  # see tox.ini
  "pytest-cov>=6 ; python_version >= '3.13'",
  "pytest-sugar>=1 ; python_version >= '3.13'",
]

# bump-my-version

[tool.bumpversion]
current_version = "0.2.2"
allow_dirty = true
files = [
  {filename = ".copier-answers.yml"},
  {filename = "docs/badges.md"},
  {filename = "docs/sphinx/conf.py"},
  {filename = "src/doctestcase/__version__.py"},
]

# hatch

[tool.hatch.build]
exclude = [
  ".just",
  "Justfile",
  "Makefile",
  "compose.yml",
]
[tool.hatch.version]
path = "src/doctestcase/__version__.py"

# mypy

[tool.mypy]
incremental = false
python_version = "3.9"
strict = true
exclude = [
  "tests/docsub",  # todo: include back when docsub typing is fixed
  "tests/usage",
]
[[tool.mypy.overrides]]
module = "tests.*"
allow_incomplete_defs = true
allow_untyped_defs = true

# pytest

[tool.pytest.ini_options]
ignore = ["tests/usage"]

# ruff

[tool.ruff]
exclude = ["tests/usage"]
[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "S"]
per-file-ignores."tests/**/*.py" = [
  "S101",  # Use of `assert` detected
  "S102",  # Use of `exec` detected
  "S603",  # `subprocess` call: check for execution of untrusted input
]
[tool.ruff.format]
quote-style = "single"
docstring-code-format = true
docstring-code-line-length = "dynamic"

# scriv

[tool.scriv]
categories = ["Security ‚ö†Ô∏è", "Breaking üî•", "Removed üí®", "Deprecated ‚ùÑÔ∏è", "Added üåø", "Changed", "Fixed", "Docs", "Misc"]
entry_title_template = "[{{ version }}](https://github.com/makukha/doctestcase/releases/tag/v{{ version }}) ‚Äî {{ date.strftime('%Y-%m-%d') }}"
format = "md"
fragment_directory = "NEWS.d"
md_header_level = "2"
new_fragment_template = "file: NEWS.d/.new_fragment.md.j2"
version = "literal: pyproject.toml: tool.bumpversion.current_version"
