
[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "dv-flow-mgr"
version = "0.0.1.13657597614a1"
dependencies = [
    'pydantic',
    'pyyaml',
    "toposort",
    "svdep"
]
authors = [
    {name = "Matthew Ballance", email = "matt.ballance@gmail.com"},
]
description = "DV Flow Manager is a build system for silicon design"
license = {file = "LICENSE" }

[project.scripts]
dfm = "dv_flow.mgr.__main__:main"

[tool.setuptools.package-data]
"dv_flow.mgr" = ['share/*']

