[project]
name = "db_hooks_manager24"
version = "0.1.2"
description = "Database manager with optional MongoDB support"
authors = [
    { name = "Aldo", email = "Aldo@test.io" },
]
readme = "README.md"
packages = [{ include = "db_hooks_manager24" }]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
mysqlclient = { version = "1.4.6", optional = true }

[project.optional-dependencies]
mysql = [ "mysqlclient>=1.3,<2.0" ]
pgsql = [ "psycopg2>=2.9,<3.0" ]
mongodb = ["pymongo (>=4.11.1,<5.0.0)"]

[tool.poetry.dev-dependencies]
pytest = "^7.0"