[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tidyflow"
version = "0.1.0"
authors = [{ name = "Ann Naser Nabil", email = "ann.n.nabil@gmail.com" }]
description = "A lightweight data preprocessing toolbox"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn"
]

[project.urls]
Homepage = "https://github.com/AnnNaser/tidyflow"
