[project]
name = "hacli"
version = "0.7.10"
description = ""
authors = [
    {name = "codehamal",email = "codehamal@example.com"}
]
readme = "README.md"
requires-python = ">=3.9.0"
dependencies = [
    "typer (>=0.15.1,<0.16.0)",
    "azure-devops (>=7.1.0b4,<8.0.0)",
    "markdown-it-py (>=3.0.0,<4.0.0)",
    "beautifulsoup4 (>=4.13.3,<5.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "gitpython (>=3.1.44,<4.0.0)",
    "azure-identity (>=1.20.0,<2.0.0)",
    "azure-keyvault-secrets (>=4.9.0,<5.0.0)",
    "azure-containerregistry (>=1.2.0,<2.0.0)",
    "pydantic (>=2.10.6,<3.0.0)",
    "fastapi (>=0.115.8,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "html2text (>=2024.2.26,<2025.0.0)",
    "prettytable (>=3.15.1,<4.0.0)",
    "tabulate (>=0.9.0,<0.10.0)",
    "pydantic-settings (>=2.8.1,<3.0.0)",
]

[tool.poetry]
packages = [{include = "hacli", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
hacli = "hacli.main:start"