[tool.poetry]
name = "kalpaa"
version = "1.2.0"
description = "Groups up and runs full run."
authors = ["Deepak Mallubhotla <dmallubhotla+github@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.10"
pdme = "^1.5.0"
deepdog = "^1.5.0"
tantri = "^1.3.0"
tomli = "^2.0.1"
dacite = "^1.9.2"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
flake8 = "^4.0.1"
mypy = ">=1.14"
pytest = ">=6"
pytest-cov = "^4.1.0"
syrupy = "^4.0.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
stage01 = "kalpaa.stages.stage01:main"
stage02 = "kalpaa.stages.stage02:main"
stage03 = "kalpaa.stages.stage03:main"
stage04 = "kalpaa.stages.stage04:main"
kalpaa = "kalpaa.stages:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--junitxml pytest.xml --cov kalpaa --cov-report=xml:coverage.xml --cov-report=html"
junit_family = "xunit1"

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[[tool.mypy.overrides]]
module = [
	"tantri.*",
	"tantri",
	"deepdog",
	"deepdog.*"
]
follow_untyped_imports = true