[tool.poetry]
name = "stefan"
version = "0.1.32"
description = "Stefan The Coder - your AI assistant"
authors = ["Martin Sumera <sumera.martin@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
stefan = "stefan.main:main"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"  # Restrict to Python 3.10.x
crewai = {extras = ["agentops"], version = "^0.80.0"}
crewai-tools = "^0.14.0"
python-dotenv = "^1.0.1"
pytest = "^8.3.3"
pydantic = "^2.10.0"
litellm = "^1.53.1"
pydantic-settings = "^2.6.1"
loguru = "^0.7.2"
pyyaml = "^6.0.2"
gspread = "^6.1.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "skip_slow: marks tests that should not be considered slow"
]
