[project]
name = "byteark-sdk"
version = "0.1.2"
description = ""
authors = [
    { name = "Piyaboot Thavilthirakul", email = "piyaboot@inox.co.th" }
]
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
pytest = "^8.3.4"
pytest-cov = "^6.0.0"

[tool.pytest.ini_options]
console_output_style = "classic"
