[project]
name = "otripy"
version = "1.0.1"
description = "A tool to plan your next trip"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "folium>=0.19.5",
    "geopy>=2.4.1",
    "lxml>=5.3.1",
    "markdown>=3.7",
    "nc-py-api>=0.19.0",
    "numpy>=2.2.3",
    "pillow>=11.1.0",
    "pyside6>=6.8.2.1",
    "typing-extensions>=4.12.2",
]
authors = [{ name = "GaÃ«l de Chalendar (aka Kleag)", email = "kleagg@gmail.com" }]
license = { text = "AGPL" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[tool.uv]
package = true

[project.scripts]
otripy = "otripy.main:main"

[project.optional-dependencies]
dev = ["pytest", "black", "ruff", "mypy"]   # Development tools
build = ["bumpver"]                   # For packaging and uploading
deploy = ["uv"]                               # Add tools needed for deployment

[bumpver]
current_version = "1.0.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit = true
tag = true
push = true  # Set to true if you want to push automatically

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"src/otripy/__init__.py" = [
    '__version__ = "{version}"',
]

