[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "diffusionlab"
version = "2.0.0"
description = "Easy no-frills Pytorch implementations of common abstractions for diffusion models."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lightning>=2.5.0.post0",
    "pytest>=8.3.4",
    "ruff>=0.9.3",
    "torch>=2.5.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/diffusionlab"]

[tool.ruff.lint]
ignore = ["E731"]  # This is the rule which prevents use of lambda expressions
