[project]
name = "api_rester"
version = "0.3.7"
authors = [
  { name="AlejandroJorge", email="a20202060@pucp.edu.pe" },
]
description = "A simple REST API client CLI utility"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {file = "LICENSE"}
dependencies = [
  "requests>=2.32.3",
  "pydantic>=2.10.6",
  "dotenv>=0.9.9"
]

[project.scripts]
api-rester = "api_rester:main"

[project.urls]
Homepage = "https://github.com/AlejandroJorge/api-rester"
Issues = "https://github.com/AlejandroJorge/api-rester/issues"
