[tool.poetry]
name = "deepkeep"
version = "1.2.12"
description = "The official Python library for the Deepkeep API"
readme = "README.md"
license = "Apache-2.0"
authors = ["DeepKeep Devs <dev@deepkeep.ai>"]
packages = [{include = "deepkeep", from = "src"}]

classifiers = [
  "Typing :: Typed",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent",
  "Operating System :: POSIX",
  "Operating System :: MacOS",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Microsoft :: Windows",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "License :: OSI Approved :: Apache Software License"
]

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
httpx = "^0.27.0"
pydantic = "^2.6.3"
typing-extensions = "^4.10.0"
anyio = "^4.3.0"
distro = "^1.9.0"
sniffio = "^1.3.1"
tqdm = "^4.66.2"
lock = "^2018.3.25.2110"
update = "^0.0.1"
requests = "^2.22.0"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.352"
mypy = "^1.8.0"
respx = "^0.20.2"
pytest = "^8.0.2"
pytest-asyncio = "^0.23.5"
ruff = "^0.3.1"
time-machine = "^2.14.0"
nox = "^2024.3.2"
dirty-equals = "^0.7.1.post0"
importlib-metadata = "^7.0.2"
types-tqdm = "^4.66.0.20240106"
types-pyaudio = "^0.2.16.20240106"

[project.urls]
Homepage = "https://deepkeep.ai"
Repository = "https://github.com/Deepkeepai/deepkeep-quickstart-python"

[tool.setuptools.package-dir]
mylib = "src/deepkeep"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.build]
include = [
  "src/*"
]

[tool.build.targets.wheel]
packages = ["src/deepkeep"]
