[project]
name = "pyvfg"
version = "3.2.0"
description = ""
readme = "README.md"
requires-python = ">= 3.13"
dependencies = [
    "pydantic >= 2.8.2",
    "jsonpatch>=1.33",
]

[[project.authors]]
name = "Jasmine Moore"
email = "jasmine.moore@verses.ai"

[[project.authors]]
name = "Alex Kiefer"
email = "alex.kiefer@verses.ai"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
