[tool.poetry]
name = "async-task-runner"
version = "1.0.3"
description = "An asyncio-based asynchronous task runner, ready to use out of the box."
authors = ["huangyanming <13528685024@163.com>"]
readme = "README.md"
packages = [{ include = "asyncrunner" }]
license = "MIT"
homepage = "https://github.com/869413421/asyncrunner"
repository = "https://github.com/869413421/asyncrunner"
documentation = "https://github.com/869413421/asyncrunner"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
