[project]
name = "cdisc-library-keyediffer"
version = "0.0.41"
description = "A library for diffing structured data, like json or xml files, where the two files being diffed share some common structure."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.12"
authors = [{ name = "Geraud Campion", email = "gcampion@cdisc.org" }]
dependencies = ["genson", "jsonpath-ng", "jsonschema", "requests", "xlsxwriter"]

[project.urls]
"Repository" = "https://github.com/cdisc-org/cdisc-library-keyediffer"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "keyediffer",
    "keyediffer.models",
    "keyediffer.resources",
    "keyediffer.utils",
]

[tool.setuptools.package-data]
"keyediffer.resources" = ["*.json"]
