[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "datamodel-router"
version = "2.1.0"
authors = [
  { name = "Tobias Ahlers", email = "93325697+TobiasAhlers@users.noreply.github.com" },
]
description = "A simple router for data_models"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  "fastapi",
  "datamodel-orm",
]
[project.optional-dependencies]
test = [
  "pytest",
  "pytest-cov",
  "httpx",
  "setuptools"
]

[project.urls]
Homepage = "https://github.com/TobiasAhlers/DataModel-Router"
Issues = "https://github.com/TobiasAhlers/DataModel-Router/issues"
