[project]
name = "mcp-server-port"
version = "0.0.12"
description = "A Model Context Protocol (MCP) server for Port.io integration"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.26.0",
    "mcp[cli]>=1.0.1",
    "python-dotenv>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
mcp-server-port = "mcp_server_port:main"

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_server_port"]

[tool.hatch.build]
include = [
    "src/mcp_server_port/**/*.py",
]
