# https://peps.python.org/pep-0621/
# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "elora"
dynamic = ["version"]
authors = [
  {name = "Mohsen Hariri", email = "mohsen.hariri@case.edu"},
]
description = "eLoRA: Efficient Rank Allocation for Budget-Constrained Fine-Tuning ðŸ§®ðŸ’°âš™ï¸ðŸŽ›ï¸"
keywords = ["Large Language Models", "Fine-Tuning", "LoRA"]
license = {text = "GPL-3.0 License"}
# https://github.com/pypi/warehouse/issues/869
readme = "README.rst"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3.10",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Operating System :: OS Independent",
]
dependencies = [
  'importlib-metadata; python_version<"3.8"',
]

[tool.setuptools]
packages = ["elora"]
include-package-data = true


[tool.setuptools.dynamic]
# version = { attr = "elora.__version__" }
version = {file = ["VERSION"]}

[tool.setuptools.package-data]
elora = ["assets/scores/**/*.json", "assets/dims/**/*.json"]


[tool.black]
line-length = 88
target-version = ["py38"]

[tool.ruff]
src = ["elora"]
target-version = "py38"

[tool.isort]
profile = "black"
known_first_party = "elora"
skip_glob = ["**/__init__.py"]
